### ISSUE TITLE
KeyError: 'project_path'

### ISSUE THREAD

**Issue by LYB030** [sxr1223/verible_formatter_sublime#1]
not work on windows and centos7 both with same error
![image](https://github.com/user-attachments/assets/137d8449-95c3-4d0c-b443-4e84cfd22b71)
![image](https://github.com/user-attachments/assets/9a6c40a6-d5b7-4f81-bb5d-b7b0d82c5df4)

**Comment by LYB030** [comment]
![image](https://github.com/user-attachments/assets/a86bb2dc-ed07-44e0-8f7a-ab40978e501b)

**Comment by sxr1223** [comment]
@LYB030 Fixed, please checkout. You can reinstall this plugin, or simply modify code as below.
In `Sublime4\Data\Packages\VeribleFormatterVerilogVeribleFormatterVerilog.py`, replace line 39
```python
project_path = view.window().extract_variables()['project_path']
```
with
```python
project_path = view.window().extract_variables().get("project_path","")
```
