### ISSUE TITLE
not work on linux due to subprocess has no attribute 'STARTIPINFO'

### ISSUE THREAD

**Issue by LYB030** [sxr1223/verible_formatter_sublime#2]
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/f0763188-7d39-4818-ab5d-15fefde24f01">
STARTIPINFO IS WORK ON WINDOWS OS ONLY

**Comment by sxr1223** [comment]
Fixed, sorry for late. I only use Windows. Update the plguin should fix that. If the bug still here, please let me know.
